name: Production Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 16.x ]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn info
      run: |
        yarn info
    - name: Yarn upgrade
      run: |
        yarn upgrade    
    - name: Yarn add yarn
      run: |
        yarn add yarn
    - name: Yarn Install
      run: |
        yarn install
    - name: Production Build
      run: |
        yarn build
